name: Auto Deploy React (Self Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code from GitHub
        uses: actions/checkout@v3

      - name: Go to project folder and update code
        run: |
          cd ~/my-app
          git fetch https://github.com/kar2911/my-app.git
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          cd ~/my-app
          npm install

      - name: Restart React App
        run: |
          pm2 restart react-app